#spring.application.name=eureka_server
spring:
  application:
    name: eureka_server
server:
  port: 1111
eureka:
  instance:
    appname: czx_app
    eviction-interval-timer-in-ms: 50000
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  server:
    enable-self-preservation: false